### ISSUE TITLE
Questions about the last segment of route

### ISSUE THREAD

**Issue by tiefan** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#10]
does it depends on any traffic lights signal for the last segment of each route of the vehicle?
does it matters wether the last end_intersection's traffic light for the corresponding lane is red or green?
how to judge the complishment for one single route? just need to get to the intersection or pass the intersection?

**Comment by zhyliu00** [comment]
Thanks for your comment. 
If a vehicle is on the last segment of its route, it will run to the end of this road. When having arrived at the end of the road, it will be set "arrived" without passing the intersection. After that, this vehicle will 'disappear'.

**Comment by IcarusWizard** [comment]
Hi, I have further questions about this topic.

Which lane will such vehicles pick? The straight one? Lane with least vehicles? Or just randomly pick one?

**Comment by zhyliu00** [comment]
Lane with least vehicles.
