### ISSUE TITLE
Q: what the dones returned by env.step() means?

### ISSUE THREAD

**Issue by Sud0x67** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#11]
Hi, sir, I am confussed with some parameters.
Is that menas every intersections stop at different time? 
Dose the env has a fixed running time for example stop at 3600 steps?
Dose max_time_epoch =3600, the env stop with 3600 steps?

**Comment by zhyliu00** [comment]
Thanks for your comment.
1. No. All agents will stop when CBEngine has run _max_time_epoch_ steps.
2. No. It will run _max_time_epoch_ steps. You could modify it in _simulator.cfg_
3. Yes.
