### ISSUE TITLE
simulation step

### ISSUE THREAD

**Issue by Wangjw6** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#12]
In the following lines proposed in the demo:
` 

        for _ in range(args.action_interval):
                # print(i)
        
                i += 1

                # Interacts with the environment and get the reward.

                observations, rewards, dones, infos = env.step(actions_)`

According to the tutorial, the simulation proceeds 10 sec for each step. Then the loop with respect to the action interval (default is 40) here may indicate the action only will be changed every 10*40 sec. Is it right?

**Comment by zhyliu00** [comment]
Thanks for your comment.
No. The action interval 40 is corresponding to 40 seconds in CBEngine, which equals 4 steps in Gym-like API.

**Comment by Wangjw6** [comment]
But inside the loop there is step function in gym-like API, which proceeds 10 sec simulation each time. Should the total simulation time for this loop equal to 10*args.action_interval?

**Comment by zhyliu00** [comment]
Yes.

**Comment by zhyliu00** [comment]
The new version of train_dqn_example.py is updated. Thanks for your comment.
