### ISSUE TITLE
Road direction at intersection?

### ISSUE THREAD

**Issue by ziruizhuang** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#13]
### 1. 
From documentation: https://kddcup2021-citybrainchallenge.readthedocs.io/en/latest/cbengine.html#road-network-data
We can see that the following road net info translates into intersection `42167350405` having a western approach `105`.
```
42167350405 56 97 45 105
```
It means that for intersection `42167350405`, road segment `105` is the `Road_8` or `inroad3`, and `105`'s lanes are `lane10`,`lane11`,`lane12` or `inroad3lane0`,`inroad3lane1`,`inroad3lane2`, with direction `inbound` to the intersection. 

However, the simulation engine gives different definition:

For vehicle at road `105`'s lane 1,
```
{vehicle_id}, {road}, {lane}, {distance}, {speed}, {start_time}, {t_ff}
0,            105,    1,      12.0,       6.0,     26.0,         77.976
```
the simulator gives lane_vehicle_number as 
```
{intersection_id}, {lane_vehicle_number}
22372852612 Environment vehicle number:  [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
42167350405 Environment vehicle number:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
```
which means that the vehicle is on intersection `42167350405`'s `lane23` or `outroad3lane1`, with direction `outbound` from the intersection,  per documentation at https://kddcup2021-citybrainchallenge.readthedocs.io/en/latest/APIs.html#simulation-step. 

The directions from simulation seem to be the exact opposite of the ones in documentation. 

### 2.
In https://kddcup2021-citybrainchallenge.readthedocs.io/en/latest/cbengine.html#road-network-data , there are two directions, dir1 and dir2. Could the documentation clarify which direction (dir1 or dir2) indicates the direction from source intersection to destination intersection?

**Comment by zhyliu00** [comment]
Thanks for your advice. We have updated the doc.

**Comment by tiefan** [comment]
> Thanks for your comment.
> Because of the irregularity of the roadnet, the direction of roads connecting to an intersection is relative. You could refer to the visualization.

Thanks for rely. 
In this case, which lane should the vehicle take? turn left or go straight ahead?
