### ISSUE TITLE
unclear road network description

### ISSUE THREAD

**Issue by namdre** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#17]
Hello,

I'm trying to interpret the road network file and came across several issues:

1.  As far as I can tell from https://kddcup2021-citybrainchallenge.readthedocs.io/en/latest/cbengine.html#road-network-data, the 'Road Dataset', specifies only the destination edge for every origin lane. How can the destination lane be identified?

2. The docs give the example road
`28571560 4353988632 93.2000000000 20 3 3 1 2`

and describe this as

Attribute Name | Example | Description
-- | -- | --
from_inter_id | 28571560 | upstream intersection ID w.r.t. dir1
to_inter_id | 4353988632 | downstream intersection ID w.r.t. dir2

From the examples it looks like they should read instead:

Attribute Name | Example | Description
-- | -- | --
from_inter_id | 28571560 | upstream intersection ID w.r.t. dir1
to_inter_id | 4353988632 | downstream intersection ID w.r.t. **dir1**
from_inter_id | 28571560 | downstream intersection ID w.r.t. dir2
to_inter_id | 4353988632 | **upstream** intersection ID w.r.t. dir2

Is that understanding correct?

3. The documentation says 
> In general, there are two directions on each road segment (i.e., dir1 and dir2)

How are unidirectional roads represented int the network format (i.e. a motorway on-ramp that only goes in one direction)?

4. In the example network https://github.com/CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit/blob/d14e2f4a345bbaf1b5ce3ad801c14459275cb1b2/data/roadnet_warm_up.txt#L39-L41

We find that we find that road '1' has a right-turn connection from the rightmost lane. However, the network topology doesn't show a right target edge. Is that an error in the network data or is the problem with my understanding of it?

Likewise a straight connection is specified for road 3 without an corresponding target edge  https://github.com/CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit/blob/d14e2f4a345bbaf1b5ce3ad801c14459275cb1b2/data/roadnet_warm_up.txt#L42-L44

![Screenshot from 2021-05-08 05-54-28](https://user-images.githubusercontent.com/6240630/117525456-b0396600-afc2-11eb-91df-1f95fb6a51a4.png)

Sorry for the wall of text (-:
Thanks for your input.

**Comment by zhyliu00** [comment]
Thanks for your comment.
1. Do you mean 'lanelink'? In CBEngine, every lane of the destination edge could be destination lane. The vehicle will choose one of them according to its route and the traffic of the road.
2. Your understanding is right. We have updated the unclear part of the document.
3. Currently there are only 2-directions roads in the roadnet. We are working on it for more realistic simulation.
4. Yes, some of the lanes don't have a destination edge. We do so because we want a standard data format(w.r.t. 24 features in observation and reward) to make participants focus on the signal control. The vehicles usually won't run on these lanes unless this road is the last road of its route.

**Comment by namdre** [comment]
1.) I was assuming that not all lanes on the  destination edge can be a destination lane. Thanks for the clarification
4.) Does this mean, that the 3-lane edge '100' with the single destination '102' has only the capacity of one lane (screenshot below)?

https://github.com/CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit/blob/d14e2f4a345bbaf1b5ce3ad801c14459275cb1b2/data/roadnet_warm_up.txt#L180-L182

![Screenshot from 2021-05-11 08-10-09](https://user-images.githubusercontent.com/6240630/117767302-08759f80-b231-11eb-89e5-7e34677f1089.png)

**Comment by zhyliu00** [comment]
4. Yes

**Comment by namdre** [comment]
Thank you very much.
