### ISSUE TITLE
Inconsistent behavior between the document and the code 

### ISSUE THREAD

**Issue by IcarusWizard** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#2]
In the document, it says whenever an agent switches its phase there will be a 5 seconds 'all red' phase to prevent any traffic. Thus, I assume if we switch the phase with a period of less than 5, there will be no vehicles passing at all. However, if we change the `green_sec`  in the starter agent from 5 to 2, the `delay_index` decreases, meaning there are still vehicles passing through. Did I miss something?

**Comment by zhyliu00** [comment]
Thanks for your comment. We are fixing this problem. Update will come soon.

**Comment by zhyliu00** [comment]
New version of CBEngine has been pushed to docker hub.

**Comment by IcarusWizard** [comment]
Thanks for the timely update!
