### ISSUE TITLE
How to random the env?

### ISSUE THREAD

**Issue by wangzelong0663** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#21]
I found that with the same config roadnet and flow file, if I set each obs the same action, and run env.step(action),  the results of the env are the same. Even if I use the code blow with the different seed:
`seed = 2021
random.seed(seed)
np.random.seed(seed)
env.seed(sedd)`

- So is there any  method to random the env ?

**Comment by zhyliu00** [comment]
Thanks for your comment.
I think the env doesn't need to randomize because roadnet and flow are set. What do _the method to random_ referring to?
