### ISSUE TITLE
submission failed but no error messgae return

### ISSUE THREAD

**Issue by Wormh0-le** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#26]
![image](https://user-images.githubusercontent.com/20257103/118754522-da7c0500-b899-11eb-9118-e87569fcae0b.png)
can anyone help me? i follow the code format in start-kit to submit，and last time i succed, now i  dont't change anything except the model will be load, it failed but   Traceback (most recent call last): error message is None. I don't know how to do.Anyone others know the possible reasons.Thanks a lot.

**Comment by wangzelong0663** [comment]
you can read the `Trackback` for detail, such as the image below, which will tell you the reason...
![image](https://user-images.githubusercontent.com/22271955/118816789-2011ef80-b8e5-11eb-9cab-d31e3f4aa7f0.png)

In your  image, the right below side also has the `Trackback` info ,you can read it carefully.
Hope this can help you.

**Comment by Wormh0-le** [comment]
> you can read the `Trackback` for detail, such as the image below, which will tell you the reason...
> ![image](https://user-images.githubusercontent.com/22271955/118816789-2011ef80-b8e5-11eb-9cab-d31e3f4aa7f0.png)
> 
> In your image, the right below side also has the `Trackback` info ,you can read it carefully.
> Hope this can help you.

thanks a lot, but as my screensnap displayed, that 's all `Trackback` info retured. I dont' know why, and i load another mod file, it works well. It 's weired, but thanks your reply.
