### ISSUE TITLE
Are left-turn traffic permitted when the through direction has green?

### ISSUE THREAD

**Issue by HaoZhouGT** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#28]
Hi I'm wondering if the left-turn traffic permitted when the through direction has green? In other words, when we set traffic light to phase 1 (through for North-South), can those left-turn vehicles find gaps and pass the intersection? 

Thanks.

**Comment by huynhnhathao** [comment]
nah the document said that `For example, if an agent is at phase 1, lane_1 and lane_7 along with all right turning lanes are passable. `, so I don't think that left-turning lanes are passable

**Comment by HaoZhouGT** [comment]
Thanks for answering but such a setting would be unrealistic though.
