### ISSUE TITLE
Question about the passable lanes of phases

### ISSUE THREAD

**Issue by huynhnhathao** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#29]
Hello, from your doc: "For example, if an agent is at phase 1, lane_1 and lane_7 along with all right turning lanes are passable", does it mean that the right turning lanes are passable at every phase from 1 to 8?

**Comment by huynhnhathao** [comment]
I have one more question, in the below image:
![image](https://user-images.githubusercontent.com/54271806/119213929-13f87e80-baed-11eb-9636-9ccb80265bed.png)
and the description of the rewards is:

The length of the value list is 24. The order of their roads is defined in 'signal' part of roadnet file and the same as in observation.

The order is :inroad0lane0, inroad0lane1, inroad0lane2, inroad1lane0 ... inroad3lane2, outroad0lane0, outroad0lane1 ...

does that mean that, the inroad0lane0 is lane 1 in the image, inroad0lane1 is lane  2, inroad0lane2 is lane 3, and outroad0lane1 is lane 13?

**Comment by Kuangqi927** [comment]
> Hello, from your doc: "For example, if an agent is at phase 1, lane_1 and lane_7 along with all right turning lanes are passable", does it mean that the right turning lanes are passable at every phase from 1 to 8?

I think so, right turning is not restricted by traffic light.
