### ISSUE TITLE
yarn start can't demostrate the visualizaton

### ISSUE THREAD

**Issue by stellarkey** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#3]
There is no error messages.

![image](https://user-images.githubusercontent.com/38290992/113510882-86d68600-958f-11eb-9c92-af6c26d88a7d.png)

But I fail to open the website " http://localhost:3000/".

![image](https://user-images.githubusercontent.com/38290992/113510960-e6cd2c80-958f-11eb-97d8-8054639ab110.png)

**Comment by stellarkey** [comment]
The modified codes are as follows:

```javascript
...
...
mapboxgl.accessToken = 'pk.eyJ1IjoidmVsb2NmYyIsImEiOiJja24zNjNkd3IxZWFjMndvOHh6M2F0dDM3In0.wyUaKKx5Ilq4QBsFh6WIxA';

class Application extends React.Component {
  mapRef = React.createRef();
  map;
  constructor(props: Props) {
    super(props);
    this.state = { clocker: 0, paused: true, code: '' };
    this.maxTime = 359
    this.trafficpos = require("./log/lightinfo.json")
    this.roadpos = require("./log/roadinfo.json")
    this.ClickStart = this.ClickStart.bind(this);
    this.ClickPause = this.ClickPause.bind(this);
    this.ClickRestart = this.ClickRestart.bind(this);
    this.ClickReset = this.ClickReset.bind(this);
    this.onChange = this.onChange.bind(this);
    setInterval(() => { this.upDate(this.map) }, 100);
  }
...
...
```

**Comment by zhyliu00** [comment]
Thanks for your comment. Can you provide your environment?

**Comment by stellarkey** [comment]
Thanks for reply. I'm using **VSCode** internal terminal to create a virtual docker environment to run the starter-kit on **Window 10**.

**Comment by zhyliu00** [comment]
Thanks for your feedback. The visualization tool is independent from the experiment package. Therefore, you can directly run "yarn start" and go to localhost:3000 in your browser both on your Windows computer. It seems the error might be induced by running the "yarn start" in the docker container while openning the browser on the host machine.

**Comment by stellarkey** [comment]
Thanks for your suggestions! It worked! I run it directly through the terminal and the localhost:3000 auto-pop out and demostrate everything well.
