### ISSUE TITLE
About dataset of local and evaluation

### ISSUE THREAD

**Issue by Zhikaiiii** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#34]
Hey, in docs, it says that ' We use exactly the same road network and traffic data for scoring your submissions'.

However, I found that it differences a lot when I run my algorithms in local use evaluate.py with service submissions result. I wonder it is my code bug or the datasets is different?

Thanks : )

**Comment by huynhnhathao** [comment]
The leaderboard really gives the same result as local evaluation to me, I think you should clone the GitHub repository again and check the result

**Comment by Zhikaiiii** [comment]
> The leaderboard really gives the same result as local evaluation to me, I think you should clone the GitHub repository again and check the result

thanks for your reply : )
I have found that if I can serve all the vehicles, the result is indeed the same.
