### ISSUE TITLE
How much RAM the demo.py script needs to run? 

### ISSUE THREAD

**Issue by ChuanyuXue** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#4]
I am trying to run the demo.py on MacOS Silicon system with the provided docker image, but it is always killed due to the memory limitation. Through the docker monitor I find it requires more than 12GB to run within 161 steps, is this memory usage normal?

I tried to change the parameter "max_time_epoch" to 120 in the cfg file then it can work, but only 4 vehicles are served.

**Comment by zhyliu00** [comment]
Thanks for your comment.
Usually, the whole process will consume about 50M memory in docker container. Your case is quite strange. Could you provide your environment?

**Comment by ChuanyuXue** [comment]
Thank you for your reply.

My environment is 

Docker version 20.10.5, build 55c4c88
macOS Big Sur Version 11.2.3
Chip Apple M1

**Comment by maxgaw** [comment]
I see the same behavior but just reaching 26 Steps with ~ 13GB of memory usage.

Docker version 20.10.5
Big Sur Version 11.2.1
Chip Apple M1

**Comment by wybiacx** [comment]
Can you compile the CBEngine library on the M1 chip macbook? So that we can debug our program locally🤔
