### ISSUE TITLE
any interface to close the useless log

### ISSUE THREAD

**Issue by KK666-AI** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#40]
Dear authors, so many useless log are printed, such as 
```
start_time_epoch = 0
max_time_epoch = 3600
report_log_rate = 10
warning_stop_time_log = 100
```
Is there any interface to close above useless log?

**Comment by Kanstarry9T** [comment]
Thanks for your comment, currently you cannot close above log, we will close above logs in the next updated version.

**Comment by KK666-AI** [comment]
ok, i see.
