### ISSUE TITLE
 how to install the system using conda rather than only docker

### ISSUE THREAD

**Issue by SHITIANYU-hue** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#5]
I have a question about the installation. I am wondering that could we install the system using conda rather than only the docker? I am trying to install it through conda, but I found that I missed the CBEngine simulator.

**Comment by Sud0x67** [comment]
Hi@SHITIANYU, I have this problem too,.Did you have addressed it?

**Comment by SHITIANYU-hue** [comment]
No..

**Comment by Sud0x67** [comment]
@SHITIANYU, Maybe you can use this version on  your own machine, I distilled the reference from  formal docker image, https://github.com/Sud0x67/city_brain_kit.git

**Comment by zhyliu00** [comment]
Thanks for your comment.
	We suggest you using docker for successful submission. We are testing the possibility of preparing environments via native installation on different operating systems. Updates will come soon.
