### ISSUE TITLE
where is the latest environment for round 3?

### ISSUE THREAD

**Issue by KK666-AI** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#51]
Dear author,

Where is the latest environment for round 3? In this [line ](https://github.com/CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit/blob/main/evaluate.py#L88) from evaluate.py in the master branch, I notice that the latest environment is updated to `from CBEngine_round3 import CBEngine_round3 as CBEngine_rllib_class`, where it invokes `from CBEngine_rllib.CBEngine_rllib import CBEngine_rllib as CBEngine_rllib_class`.
There occurs the following error:
`ModuleNotFoundError: No module named 'CBEngine_rllib'`

**Comment by behrisch** [comment]
You probably need to update your docker container to 0.1.3

**Comment by Kanstarry9T** [comment]
You need to pull the latest docker container, the newest docker version is 0.1.3.

**Comment by Kanstarry9T** [comment]
You need to pull the latest docker container, the newest docker version is 0.1.3. Please refer to this link: https://kddcup2021-citybrainchallenge.readthedocs.io/en/final-phase/try-it-yourself.html#installation

**Comment by KK666-AI** [comment]
Thanks.

**Comment by KK666-AI** [comment]
One more question, i notice that in your installation instruction, you say ` multi-flow training` , do you mean the round 3 supports vectorized environment?

**Comment by Kanstarry9T** [comment]
multi-flow training means that training your model on multiple traffic flow settings.
