### ISSUE TITLE
how to access roadnet info in agent?

### ISSUE THREAD

**Issue by tiefan** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#8]
it seems that the "path" args associated with the roadnet file, only passed to the evaluate.py file, and the agent cannot acquire the "path" of roadnet.txt.
obviously, the roadnet info is so essential, just like the 8 phases of the intersection. i can not solve the problem without these information.
if you do not agree, convince me; if you agree, tell me how

**Comment by zhyliu00** [comment]
Thanks for your comment.
You could load the roadnet info by copy _roadnet.txt_ to your _agent_ folder, and load the information you need via modifying agent.py. We will add new interface for load roadnet information in agent.py soon.

**Comment by tiefan** [comment]
Thanks
